# Generated by Django 5.1 on 2024-09-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacocoworking',
            name='prioridade',
            field=models.IntegerField(default=0),
        ),
    ]
