# Generated by Django 5.1 on 2024-09-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_espacocoworking_prioridade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espacocoworking',
            options={'ordering': ['prioridade'], 'verbose_name': 'Espaço de Coworking', 'verbose_name_plural': 'Espaços de Coworking'},
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='acessibilidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='acesso24h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='agencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='ar_condicionado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='area_alimentacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='auditorio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='biblioteca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='cabine_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='cafe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='cafeteria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='cep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='cha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='coliving',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='conta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='cozinha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='descricao_espaco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='email_gerente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='email_proprietario',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='espaco_convivencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='espaco_eventos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='espaco_pet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='estudio_gravacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='foto_horizontal',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_espaco/'),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='fotos_area_compartilhada',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_areas_compartilhadas/'),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='fotos_area_comum',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_areas_comuns/'),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='fotos_salas_privativas',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_salas_privativas/'),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='frase_destaque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='galeria_arte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='geladeira',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='gerador_eletricidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='jardim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='linkedin',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='lounge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='massagem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='nome_espaco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='nome_gerente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='nome_proprietario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='outras_fotos',
            field=models.ImageField(blank=True, null=True, upload_to='outras_fotos/'),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='outros_diferenciais',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='palavras_chave',
            field=models.TextField(blank=True, help_text='Separado por ;', null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='pix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='playground_kids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='quadro_branco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='recepcao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='restaurante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='sala_descompressao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='sala_jogos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='telefone_gerente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='telefone_proprietario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='tipo_conta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='tipo_pix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='titular_conta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='varanda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='velocidade_internet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='vestuario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
