# Generated by Django 5.1 on 2024-09-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_espacocoworking_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espacocoworking',
            name='descricao_espaco',
        ),
        migrations.AlterField(
            model_name='espacocoworking',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='espacocoworking',
            name='palavras_chave',
            field=models.TextField(blank=True, help_text='Separado por -', null=True),
        ),
    ]
