# Generated by Django 5.1 on 2024-09-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_remove_espacocoworking_descricao_espaco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
