# Generated by Django 5.1 on 2024-09-06 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_recursosespacocoworking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recursosespacocoworking',
            options={'ordering': ['nome_recurso'], 'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
        migrations.RemoveField(
            model_name='recursosespacocoworking',
            name='espaco_coworking',
        ),
    ]
