# Generated by Django 5.1 on 2024-09-06 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_alter_recursosespacocoworking_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecursosEspacoCoworking',
        ),
    ]
