# Generated by Django 5.1 on 2024-09-11 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_recursosespacocoworking'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='recurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.recursosespacocoworking'),
        ),
    ]
