# Generated by Django 5.1 on 2024-09-11 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_reserva_recurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='recurso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservas.recursosespacocoworking'),
            preserve_default=False,
        ),
    ]
