# Generated by Django 5.1 on 2024-09-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_imagemespacocoworking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espacocoworking',
            name='foto',
        ),
    ]
